name: Ingest Obsidian Notes

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find notes to ingest
   :contentReference[oaicite:0]{index=0}
          echo "files=$joined" >> $GITHUB:contentReference[oaicite:1]{index=1}    env:
          SUPABASE_ANON_K:contentReference[oaicite:2]{index=2}ts.SUPABASE_SERVICE_ROLE_KEY }}
 :contentReference[oaicite:3]{index=3}          IFS='|:|':contentReference[oaicite:4]{index=4}iles }}"

          for file in "${files[@]}"; do
          :contentReference[oaicite:5]{index=5}t-matter (between the f:contentReference[oaicite:6]{index=6} sed -n:contentReference[oaicite:7]{index=7}8-4631-:contentReference[oaicite:8]{index=8})
     :contentReference[oaicite:9]{index=9}
            # Buil:contentReference[oaicite:10]{index=10};/^---$/d;s/^- //p:contentReference[oaicite:11]{index=11}]')

            # Extr:contentReference[oaicite:12]{index=12}
            content=$(aw:contentReference[oaicite:13]{index=13}              | jq -Rs:contentReference[oaicite:14]{index=14}yload=$(
            :contentReference[oaicite:15]{index=15}         :contentReference[oaicite:16]{index=16}ate" :contentReference[oaicite:17]{index=17}h: $path, type: $type, date: $date, tags: $tags, content: $content }'
            )

            # Send to Supabase
            curl -s -w "\nHTTP_CODE=%{http_code}" \
              -X POST https://sffsnpwqifdiwcepotdb.functions.supabase.co/ingest \
              -H "apikey: $SUPABASE_ANON_KEY" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -H "Content-Type: application/json" \
              -d "$payload"
          done



