name: Ingest Obsidian Notes

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find changed markdown files
        id: find_notes
        run: |
          raw=$(git diff --name-only ${{ github.sha }} ${{ github.sha }}~1 | grep '\.md$' || true)
          joined=$(echo "$raw" | paste -sd '|:|' -)
          echo "files=$joined" >> $GITHUB_OUTPUT
          
      - name: Filter frontmatter & call Supabase
        if: steps.find_notes.outputs.files != ''
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          sudo apt-get update && sudo apt-get install -y yq jq

          IFS='|' read -r -a files <<< "${{ steps.find_notes.outputs.files }}"
          for file in "${files[@]}"; do
            [[ -f "$file" ]] || continue
            grep -q '^ingest: true' "$file" || continue

            pid="48245528-5e58-4631-9755-cddd1a40a4a6"
            tp=$(yq e '.type' "$file")
            dt=$(yq e '.date' "$file")
            tg=$(yq e '.tags | @json' "$file")
            ct=$(awk 'f&&!--/^---$/{print} /^---$/{f=!f}' "$file" | jq -Rs .)

            payload=$(
              jq -n \
                --arg persona_id "$pid" \
                --arg doc_path "$file" \
                --arg type "$tp" \
                --arg date "$dt" \
                --argjson tags "$tg" \
                --arg content "$ct" \
                '{ persona_id, doc_path, type, date, tags, content }'
            )

            curl -s -w "\nHTTP=%{http_code}\n" \
              -X POST https://sffsnpwqifdiwcepotdb.functions.supabase.co/ingest \
              -H "apikey: $SUPABASE_ANON_KEY" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -H "Content-Type: application/json" \
              -d "$payload"
          done

