name: Ingest Obsidian Notes

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find notes to ingest
        id: find_notes
        run: |
          raw=$(git diff --name-only ${{ github.sha }} ${{ github.sha }}~1 | grep '\.md$' || true)
          joined=$(echo "$raw" | paste -sd '|:|' -)
          echo "files=$joined" >> $GITHUB_OUTPUT

      - name: Filter frontmatter & call Supabase
        if: steps.find_notes.outputs.files != ''
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -euxo pipefail

          # split the filenames into an array
          IFS='|:|' read -r -a files <<< "${{ steps.find_notes.outputs.files }}"

          for file in "${files[@]}"; do
            [[ -f "$file" ]] || { echo "File not found: $file"; continue; }

            # extract front-matter (lines 2 through the line before the second '---')
            front=$(sed -n '1,/^---$/p' "$file" | sed '1d;$d')

            # ingest flag
            ingest_flag=$(echo "$front" | sed -n 's/^ingest:[[:space:]]*//p')
            [[ "$ingest_flag" == "true" ]] || { echo "Skipping $file (no ingest:true)"; continue; }

            persona_id="48245528-5e58-4631-9755-cddd1a40a4a6"
            type=$(echo "$front" | sed -n 's/^type:[[:space:]]*//p')
            date=$(echo "$front" | sed -n 's/^date:[[:space:]]*//p')

            # tags: grab lines under 'tags:' until indent ends
            tags=$(echo "$front" \
              | awk '/^tags:/{flag=1; next} /^  - /{print $3} flag && !/^  - /{exit}' \
              | jq -R -s -c 'split("\n")[:-1]')

            # body: print everything after the second '---'
            content=$(awk 'BEGIN{count=0}
/^---$/ { count++; next }
count>=2 { print }
' "$file" | jq -Rs .)

            # build payload
            payload=$(
              jq -n \
                --arg pid "$persona_id" \
                --arg path "$file" \
                --arg type "$type" \
                --arg date "$date" \
                --argjson tags "$tags" \
                --arg content "$content" \
                '{ persona_id: $pid, doc_path: $path, type: $type, date: $date, tags: $tags, content: $content }'
            )

            # send to Supabase
            curl -s -w "\nHTTP_CODE=%{http_code}" \
              -X POST https://sffsnpwqifdiwcepotdb.functions.supabase.co/ingest \
              -H "apikey: $SUPABASE_ANON_KEY" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -H "Content-Type: application/json" \
              -d "$payload"
          done


